# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - testapp

on:
  push:
    branches:
      - main
    paths:
      - 'python-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'python-app/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: testapp
  AZURE_WEBAPP_PACKAGE_PATH: './python-app'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          source venv/bin/activate
          pip install -r requirements.txt
        
      - name: Install testing dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          source venv/bin/activate
          pip install pytest pytest-asyncio httpx
          
      - name: Run tests with pytest
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          source venv/bin/activate
          echo "Running Python tests..."
          if pytest tests/ -v --tb=short; then
            echo "✅ All tests passed successfully"
          else
            echo "❌ Some tests failed - see details above"
            echo "🔍 Test failure summary:"
            pytest tests/ --tb=no -q || true
            echo "📋 This will prevent deployment to production"
            exit 1
          fi

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0A6E1086C66D411499E8274F1B35E5AB }}
          package: .
        continue-on-error: false
        
      - name: Report deployment success
        if: success()
        run: |
          echo "🚀 Deployment to ${{ env.AZURE_WEBAPP_NAME }} completed successfully!"
          echo "📱 App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
          
      - name: Report deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to ${{ env.AZURE_WEBAPP_NAME }} failed!"
          echo "🔍 Please check the logs above for error details."
          echo "🛠️  Common issues:"
          echo "   - Verify Azure publish profile secret is correctly configured"
          echo "   - Check that the Azure Web App '${{ env.AZURE_WEBAPP_NAME }}' exists"
          echo "   - Ensure Python 3.12 is supported on the target App Service"
          exit 1